### ISSUE TITLE
Fix Request: cannot export to pdf due to this plugin

### ISSUE THREAD

**Issue by Maxlinn** [stargrey/obsidian-better-codeblock#7]
Hi there, thanks for bringing this plugin and i really love it.
However, when i tried to `Exported to PDF` as i often do, it tells me `failed to export`.

I checked `console` section is developer's mode, traceback mentioned this plugin.
A markdown document without any codeblock can be exported successfully.
Maybe it caused by other plugins other than this one, but i have no idea what's happening.

Sincerely hope you could help. `Exported to PDF` is a function i use much often to create handouts.
Thanks in advance!

Error screenshot:
![img](https://user-images.githubusercontent.com/43326876/173631067-524b65d6-681a-4883-adab-ee5ab4cb55c2.png)
Code that mentioned in the trackback of this plugin:
```js
  let codeBlockFirstLine = view.editor.getLine(codeBlock.lineStart);
```

**Comment by lethefrost** [comment]
Same issue here, @stargrey any solution? Thank you so much!

**Comment by stargrey** [comment]
@lethefrost @Maxlinn 
Sorry for the long wait, this issue may be fixed, but export PDF cannot be linefeed, I found it has different width when export PDF, so I can't measure its height

**Comment by Maxlinn** [comment]
thanks for this one too! sorry for the late reply!
