### ISSUE TITLE
Fix request: code line number goes wrong then single line is too long

### ISSUE THREAD

**Issue by Maxlinn** [stargrey/obsidian-better-codeblock#8]
Hi there, thanks for introducing this plugin!

Recently i discover that, when a single line of code is too long, 
obsidian will display it into two or more lines, 
but logically they belong to one line of markdown(line number of obsidian proves that).

However, this plugin will not skip the overflow content, instead, it will continue to label line number, casuing the line number goes wrong.

I intentionally squeeze the width of obsidian to make it more obvious.
![image](https://user-images.githubusercontent.com/43326876/173997099-3f002e0e-90a6-4ed6-90fc-68b7329b3e51.png)

Sincerely thanks if you could look into it : )

**Comment by stargrey** [comment]
抱歉久等了，现在这个问题应该解决了，不过有时候会出现显示错误，切换下预览模式或者重新打开文件就好

**Comment by Maxlinn** [comment]
sincerely appreciate your effort! sorry for the late reply ;)
