### ISSUE TITLE
Line number for last line in yaml frontmatter is missing

### ISSUE THREAD

**Issue by stainge** [stargrey/obsidian-better-codeblock#9]
![image](https://user-images.githubusercontent.com/48624558/174281850-b35bc405-6908-4e79-b71d-e14f41a9400c.png)

**Comment by stargrey** [comment]
Does the problem still exist? I can't reproduce it

**Comment by stargrey** [comment]
I can't reproduce it, it shows no problem to me. Only in Yaml?
![image](https://imgur.com/nPYtGQ3.png)

**Comment by stargrey** [comment]
麻烦在编辑模式下截个图，我看看原文是怎么写的

**Comment by stargrey** [comment]
修复了，一时半会我都想不到还有frontmatter这功能来着……
在[obsidian-code-block-enhancer](https://github.com/nyable/obsidian-code-block-enhancer)上也有是因为我部分代码从那复制来的，继承bug了……

**Comment by stainge** [comment]
问题已解决，辛苦开发者了
